### ISSUE TITLE
timeout of "hello1" will disappear.

### ISSUE THREAD

**Issue by yigaza** [gzz2000/MessageQueue#1]
q.setTimeout("hello2", 1500); //ok
    q.setTimeout("hello1", 600);  //disappear

the break at line:
 if (s == "end") break;

**Comment by yigaza** [comment]
the break at line:
 if (s == "end") break;

**Comment by yigaza** [comment]
the break at line:
 if (s == "end") break;

**Comment by gzz2000** [comment]
Hello! Can you provide a full example so I can try reproduce?
